/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessToken: () => import('#controllers/access_token_controller'),
  Departamentos: () => import('#controllers/departamentos_controller'),
  Instituciones: () => import('#controllers/instituciones_controller'),
  Municipios: () => import('#controllers/municipios_controller'),
  Problematicas: () => import('#controllers/problematicas_controller'),
  Profile: () => import('#controllers/profile_controller'),
  User: () => import('#controllers/user_controller'),
  Reportes: () => import('#controllers/reportes_controller'),
}
