/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class DepartamentoSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'nomDepartamento', 'updatedAt'] as const
  $columns = DepartamentoSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare nomDepartamento: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class DetallereporteSchema extends BaseModel {
  static $columns = ['createdAt', 'descripcion', 'fechaSeguimiento', 'id', 'idReporte', 'idUsuario', 'updatedAt'] as const
  $columns = DetallereporteSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare descripcion: string
  @column.date()
  declare fechaSeguimiento: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare idReporte: number
  @column()
  declare idUsuario: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class InstitucioneSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'idMunicipio', 'nombreInstitucion', 'updatedAt'] as const
  $columns = InstitucioneSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare idMunicipio: number | null
  @column()
  declare nombreInstitucion: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class MunicipioSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'idDepartamento', 'nomMunicipio', 'updatedAt'] as const
  $columns = MunicipioSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare idDepartamento: number
  @column()
  declare nomMunicipio: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProblematicaSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'problema', 'updatedAt'] as const
  $columns = ProblematicaSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare problema: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ReporteSchema extends BaseModel {
  static $columns = ['estado', 'fechaFin', 'fechaGen', 'formato', 'id', 'idInstitucion', 'idProblematica', 'idSector', 'idUsuario', 'nvlPrioridad', 'ubicacion'] as const
  $columns = ReporteSchema.$columns
  @column()
  declare estado: string | null
  @column.date()
  declare fechaFin: DateTime | null
  @column.dateTime()
  declare fechaGen: DateTime
  @column()
  declare formato: any | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare idInstitucion: number
  @column()
  declare idProblematica: number
  @column()
  declare idSector: number | null
  @column()
  declare idUsuario: number
  @column()
  declare nvlPrioridad: number | null
  @column()
  declare ubicacion: string
}

export class RoleSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'rol', 'updatedAt'] as const
  $columns = RoleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare rol: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SectoreSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'idMunicipios', 'nombreSector', 'updatedAt'] as const
  $columns = SectoreSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare idMunicipios: number
  @column()
  declare nombreSector: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UsuarioSchema extends BaseModel {
  static $columns = ['apellidos', 'contrasena', 'correo', 'createdAt', 'id', 'idInstitucion', 'idRol', 'idSector', 'nombres', 'numeroCedula', 'sexo', 'updatedAt'] as const
  $columns = UsuarioSchema.$columns
  @column()
  declare apellidos: string
  @column()
  declare contrasena: string | null
  @column()
  declare correo: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare idInstitucion: number | null
  @column()
  declare idRol: number
  @column()
  declare idSector: number | null
  @column()
  declare nombres: string
  @column()
  declare numeroCedula: string
  @column()
  declare sexo: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
